# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13ada9baebed3366dbb90f007b503fa3f9708f5064427bbaa34047e8bfefbd8f9d45e5735273b1c97ea3abf76995a6ef6fca8ac5406e65bc752e0f4da57a2634

test:
  secret_key_base: 684a152e0fcde0cb58ad82bc529598a178c390d1b8fe724a21886c7f1c13989dbeeaba38bca97d86b17311e25c14a931228329164d8f8415aaabcc9a0f66f73c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
